Typofix202403
microsoft/MicroHack pull request #152
Opened 2024-03-22 12:09 UTC by cpinotossi

2024-03-22 14:31 UTC, ajendreieckm requested changes

2024-03-22 14:31 UTC, ajendreieckm commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/README.md
> +- Resource utilization based insights to identdeify servers and workloads that are ideal for cloud.
It was correct. Identify and not Identdeify.

2024-03-22 14:31 UTC, ajendreieckm commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-1/solution.md
>  Duration: 30 minutes
It's duplicated. Please remove one.

2024-03-22 14:31 UTC, ajendreieckm commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-1/solution.md
>  - Please ensure that you successfully verified the [General prerequisits](../../README.md#general-prerequisites) before continuing with this challenge.
Also duplicated. Please remove one.

2024-03-22 14:31 UTC, ajendreieckm commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-1/solution.md
>  ![Login from remote shell with device code](./img/mh.linux.login.gif)
also duplicated. Please remove one.

2024-03-22 14:31 UTC, ajendreieckm commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-1/solution.md
> +currentUserObjectId=$(az ad signed-in-user show --query id -o tsv)
duplicated.

2024-03-22 14:31 UTC, ajendreieckm commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-2/solution.md
> +
duplicated.

2024-03-22 14:31 UTC, ajendreieckm commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-2/solution.md
>  #### [OPTIONAL] Create the Azure Migrate Appliance VM via Azure Resource Manager Template (Bicep) instead of the Azure Portal
duplicated

2024-03-22 14:31 UTC, ajendreieckm commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-2/solution.md
> +#### Log into the Azure Migrate Appliance VM via Azure Bastion
duplicated

2024-03-22 14:31 UTC, ajendreieckm commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-2/solution.md
> +> [!IMPORTANT] You will need to install Microsof Edge Browser or Chrome on the Azure Migrate Appliance VM. Internet Explorer 11 is not supported.
broken schema somewhere. It does not look like the purple important block.

2024-03-22 16:18 UTC, cpinotossi commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-1/solution.md
>  Duration: 30 minutes
done

2024-03-22 16:18 UTC, cpinotossi commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-1/solution.md
>  - Please ensure that you successfully verified the [General prerequisits](../../README.md#general-prerequisites) before continuing with this challenge.
done

2024-03-22 16:18 UTC, cpinotossi commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-1/solution.md
>  ![Login from remote shell with device code](./img/mh.linux.login.gif)
done

2024-03-22 16:19 UTC, cpinotossi commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-1/solution.md
> +currentUserObjectId=$(az ad signed-in-user show --query id -o tsv)
done

2024-03-22 16:19 UTC, cpinotossi commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-2/solution.md
> +
done

2024-03-22 16:19 UTC, cpinotossi commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-2/solution.md
>  #### [OPTIONAL] Create the Azure Migrate Appliance VM via Azure Resource Manager Template (Bicep) instead of the Azure Portal
done

2024-03-22 16:19 UTC, cpinotossi commented on 03-Azure/01-03-Infrastructure/08_Migration_Datacenter_Linux/walkthrough/challenge-2/solution.md
> +> [!IMPORTANT] You will need to install Microsof Edge Browser or Chrome on the Azure Migrate Appliance VM. Internet Explorer 11 is not supported.
done

2024-04-08 13:29 UTC, ajendreieckm approved these changes

2024-04-08 13:29 UTC, merged